# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pandora/Scripts/UserInterfacesPandora/PandoraPythonSubmitter.ui'
#
# Created: Mon May 16 00:11:59 2022
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlg_pandoraSubmitter(object):
    def setupUi(self, dlg_pandoraSubmitter):
        dlg_pandoraSubmitter.setObjectName("dlg_pandoraSubmitter")
        dlg_pandoraSubmitter.resize(431, 561)
        self.verticalLayout = QtGui.QVBoxLayout(dlg_pandoraSubmitter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(dlg_pandoraSubmitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 411, 541))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gb_filename = QtGui.QWidget(self.groupBox_2)
        self.gb_filename.setObjectName("gb_filename")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.gb_filename)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.l_filename = QtGui.QLabel(self.gb_filename)
        self.l_filename.setObjectName("l_filename")
        self.horizontalLayout_13.addWidget(self.l_filename)
        self.e_filename = QtGui.QLineEdit(self.gb_filename)
        self.e_filename.setObjectName("e_filename")
        self.horizontalLayout_13.addWidget(self.e_filename)
        self.b_browseFilename = QtGui.QPushButton(self.gb_filename)
        self.b_browseFilename.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseFilename.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseFilename.setFont(font)
        self.b_browseFilename.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseFilename.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseFilename.setObjectName("b_browseFilename")
        self.horizontalLayout_13.addWidget(self.b_browseFilename)
        self.verticalLayout_4.addWidget(self.gb_filename)
        self.gb_args = QtGui.QWidget(self.groupBox_2)
        self.gb_args.setObjectName("gb_args")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gb_args)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.l_args = QtGui.QLabel(self.gb_args)
        self.l_args.setMinimumSize(QtCore.QSize(40, 0))
        self.l_args.setMaximumSize(QtCore.QSize(40, 16777215))
        self.l_args.setObjectName("l_args")
        self.horizontalLayout_5.addWidget(self.l_args)
        spacerItem = QtGui.QSpacerItem(5, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.lineEdit = QtGui.QLineEdit(self.gb_args)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout_4.addWidget(self.gb_args)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.f_taskname = QtGui.QWidget(self.groupBox)
        self.f_taskname.setObjectName("f_taskname")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.f_taskname)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.l_projectName = QtGui.QLabel(self.f_taskname)
        self.l_projectName.setObjectName("l_projectName")
        self.horizontalLayout_11.addWidget(self.l_projectName)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.e_projectName = QtGui.QLineEdit(self.f_taskname)
        self.e_projectName.setMinimumSize(QtCore.QSize(200, 0))
        self.e_projectName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.e_projectName.setObjectName("e_projectName")
        self.horizontalLayout_11.addWidget(self.e_projectName)
        self.verticalLayout_2.addWidget(self.f_taskname)
        self.w_jobname = QtGui.QWidget(self.groupBox)
        self.w_jobname.setObjectName("w_jobname")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.w_jobname)
        self.horizontalLayout_10.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.l_jobName = QtGui.QLabel(self.w_jobname)
        self.l_jobName.setObjectName("l_jobName")
        self.horizontalLayout_10.addWidget(self.l_jobName)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.e_jobName = QtGui.QLineEdit(self.w_jobname)
        self.e_jobName.setMinimumSize(QtCore.QSize(200, 0))
        self.e_jobName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.e_jobName.setObjectName("e_jobName")
        self.horizontalLayout_10.addWidget(self.e_jobName)
        self.verticalLayout_2.addWidget(self.w_jobname)
        self.f_rjPrio_2 = QtGui.QWidget(self.groupBox)
        self.f_rjPrio_2.setObjectName("f_rjPrio_2")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.f_rjPrio_2)
        self.horizontalLayout_25.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.l_prio = QtGui.QLabel(self.f_rjPrio_2)
        self.l_prio.setObjectName("l_prio")
        self.horizontalLayout_25.addWidget(self.l_prio)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem3)
        self.sp_priority = QtGui.QSpinBox(self.f_rjPrio_2)
        self.sp_priority.setMaximum(100)
        self.sp_priority.setProperty("value", 50)
        self.sp_priority.setObjectName("sp_priority")
        self.horizontalLayout_25.addWidget(self.sp_priority)
        self.verticalLayout_2.addWidget(self.f_rjPrio_2)
        self.f_rjWidgetsPerTask_2 = QtGui.QWidget(self.groupBox)
        self.f_rjWidgetsPerTask_2.setObjectName("f_rjWidgetsPerTask_2")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.f_rjWidgetsPerTask_2)
        self.horizontalLayout_30.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.l_framesPerTask = QtGui.QLabel(self.f_rjWidgetsPerTask_2)
        self.l_framesPerTask.setObjectName("l_framesPerTask")
        self.horizontalLayout_30.addWidget(self.l_framesPerTask)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem4)
        self.sp_framesPerTask = QtGui.QSpinBox(self.f_rjWidgetsPerTask_2)
        self.sp_framesPerTask.setMaximum(9999)
        self.sp_framesPerTask.setProperty("value", 5)
        self.sp_framesPerTask.setObjectName("sp_framesPerTask")
        self.horizontalLayout_30.addWidget(self.sp_framesPerTask)
        self.verticalLayout_2.addWidget(self.f_rjWidgetsPerTask_2)
        self.f_rjTimeout = QtGui.QWidget(self.groupBox)
        self.f_rjTimeout.setObjectName("f_rjTimeout")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.f_rjTimeout)
        self.horizontalLayout_31.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.l_rjTimeout = QtGui.QLabel(self.f_rjTimeout)
        self.l_rjTimeout.setObjectName("l_rjTimeout")
        self.horizontalLayout_31.addWidget(self.l_rjTimeout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem5)
        self.sp_rjTimeout = QtGui.QSpinBox(self.f_rjTimeout)
        self.sp_rjTimeout.setMinimum(1)
        self.sp_rjTimeout.setMaximum(9999)
        self.sp_rjTimeout.setProperty("value", 180)
        self.sp_rjTimeout.setObjectName("sp_rjTimeout")
        self.horizontalLayout_31.addWidget(self.sp_rjTimeout)
        self.verticalLayout_2.addWidget(self.f_rjTimeout)
        self.w_concurrent = QtGui.QWidget(self.groupBox)
        self.w_concurrent.setObjectName("w_concurrent")
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.w_concurrent)
        self.horizontalLayout_32.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.l_concurrent = QtGui.QLabel(self.w_concurrent)
        self.l_concurrent.setObjectName("l_concurrent")
        self.horizontalLayout_32.addWidget(self.l_concurrent)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem6)
        self.sp_concurrent = QtGui.QSpinBox(self.w_concurrent)
        self.sp_concurrent.setMinimum(1)
        self.sp_concurrent.setMaximum(9999)
        self.sp_concurrent.setProperty("value", 1)
        self.sp_concurrent.setObjectName("sp_concurrent")
        self.horizontalLayout_32.addWidget(self.sp_concurrent)
        self.verticalLayout_2.addWidget(self.w_concurrent)
        self.f_suspended = QtGui.QWidget(self.groupBox)
        self.f_suspended.setObjectName("f_suspended")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.f_suspended)
        self.horizontalLayout_29.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.l_submitSuspended = QtGui.QLabel(self.f_suspended)
        self.l_submitSuspended.setObjectName("l_submitSuspended")
        self.horizontalLayout_29.addWidget(self.l_submitSuspended)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem7)
        self.chb_suspended = QtGui.QCheckBox(self.f_suspended)
        self.chb_suspended.setText("")
        self.chb_suspended.setChecked(False)
        self.chb_suspended.setObjectName("chb_suspended")
        self.horizontalLayout_29.addWidget(self.chb_suspended)
        self.verticalLayout_2.addWidget(self.f_suspended)
        self.f_osDependencies = QtGui.QWidget(self.groupBox)
        self.f_osDependencies.setObjectName("f_osDependencies")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.f_osDependencies)
        self.horizontalLayout_28.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.l_submitDependent = QtGui.QLabel(self.f_osDependencies)
        self.l_submitDependent.setObjectName("l_submitDependent")
        self.horizontalLayout_28.addWidget(self.l_submitDependent)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem8)
        self.chb_dependencies = QtGui.QCheckBox(self.f_osDependencies)
        self.chb_dependencies.setText("")
        self.chb_dependencies.setChecked(False)
        self.chb_dependencies.setObjectName("chb_dependencies")
        self.horizontalLayout_28.addWidget(self.chb_dependencies)
        self.verticalLayout_2.addWidget(self.f_osDependencies)
        self.f_osUpload = QtGui.QWidget(self.groupBox)
        self.f_osUpload.setObjectName("f_osUpload")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.f_osUpload)
        self.horizontalLayout_23.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.l_uploadOutput = QtGui.QLabel(self.f_osUpload)
        self.l_uploadOutput.setObjectName("l_uploadOutput")
        self.horizontalLayout_23.addWidget(self.l_uploadOutput)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem9)
        self.chb_uploadOutput = QtGui.QCheckBox(self.f_osUpload)
        self.chb_uploadOutput.setText("")
        self.chb_uploadOutput.setChecked(False)
        self.chb_uploadOutput.setObjectName("chb_uploadOutput")
        self.horizontalLayout_23.addWidget(self.chb_uploadOutput)
        self.verticalLayout_2.addWidget(self.f_osUpload)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem10 = QtGui.QSpacerItem(10, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.b_submit = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.b_submit.setObjectName("b_submit")
        self.verticalLayout_3.addWidget(self.b_submit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(dlg_pandoraSubmitter)
        QtCore.QMetaObject.connectSlotsByName(dlg_pandoraSubmitter)

    def retranslateUi(self, dlg_pandoraSubmitter):
        dlg_pandoraSubmitter.setWindowTitle(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Submit Pandora renderjob", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Scene settings", None, QtGui.QApplication.UnicodeUTF8))
        self.l_filename.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseFilename.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_args.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Args:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Job settings", None, QtGui.QApplication.UnicodeUTF8))
        self.l_projectName.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Projectname:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_jobName.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Jobname:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_prio.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_framesPerTask.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Frames per Task:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rjTimeout.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Task Timeout (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.l_concurrent.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Concurrent tasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_submitSuspended.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Submit suspended:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_submitDependent.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Submit dependent files:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_uploadOutput.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Upload output:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_submit.setText(QtGui.QApplication.translate("dlg_pandoraSubmitter", "Submit", None, QtGui.QApplication.UnicodeUTF8))

